name: Get tag from commit

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  get-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Commit ID
      run: |
        commit_id=${{ github.sha }}
        echo "$commit_id"

    - name: Print Tags
      run: git tag --list

    - name: Describe Commit
      run: git describe --all

    - name: show GITHUB_REF_NAME
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"