name: Get tag from commit

on:
  workflow_dispatch:
    inputs:
      app: 
        type: choice
        description: Select the app to build
        required: true
        options:
        - all
        - affected
        - frontend
        - backend
      type: 
        type: choice
        description: Select the build type
        required: true
        options:
        - custom
        - release
        - hotfix
env:
  ALLOWED_USERS: ${{ vars.prod.ALLOWED_USERS }}
  ALLOWED_USERS_DEV: ${{ vars.dev.ALLOWED_USERS }}
jobs:
  is-run-allowed:
    runs-on: ubuntu-22.04
    outputs:
      IS_ALLOWED: ${{ steps.check-user-list.outputs.IS_ALLOWED }}
    steps:
    - name: Check if actor is in allowed-users-list
      id: check-user-list
      run: |
        actor=${{ github.actor }}
        echo -e "Allowed users list: $ALLOWED_USERS\n $ALLOWED_USERS_DEV"
        echo "GitHub Actor: $actor"
        echo "IS_ALLOWED=0" >> $GITHUB_OUTPUT

  prepare-env:
    needs:
      - is-run-allowed
    if: needs.is-run-allowed.outputs.IS_ALLOWED == 0
    runs-on: ubuntu-22.04
    steps:
    - name: Test
      id: test-condition
      run: |
        echo "IS_ALLOWED={{ needs.is-run-allowed.outputs.IS_ALLOWED }}"
        echo "Job is not skipped"
  get-tag:
    needs:
      - is-run-allowed
    if: needs.is-run-allowed.outputs.IS_ALLOWED > 0
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Commit ID
      run: |
        commit_id=${{ github.sha }}
        echo "$commit_id"

    - name: Print Tags
      run: git tag --list

    - name: Describe Commit
      run: git describe --all

    - name: show GITHUB_REF_NAME
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"