name: Get tag from commit

on:
  workflow_dispatch:
    inputs:
      app: 
        type: choice
        description: Select the app to build
        required: true
        options:
        - all
        - affected
        - frontend
        - backend
      type: 
        type: choice
        description: Select the build type
        required: true
        options:
        - custom
        - release
        - hotfix
        - other
      environment: 
        type: choice
        description: Select the deployment environment
        required: true
        options:
        - prod
        - dev
        - qa
env:
  ALLOWED_USERS: ${{ vars.ALLOWED_USERS }}
jobs:
  check-before-run:
    runs-on: ubuntu-22.04
    outputs:
      IS_ALLOWED: ${{ steps.check-user-list.outputs.IS_ALLOWED }}
      IS_CORRECT: ${{ steps.check-inputs.outputs.IS_CORRECT }}
    steps:
    - name: Check if actor is in allowed-users-list
      id: check-user-list
      run: |
        actor=${{ github.actor }}
        echo "IS_ALLOWED=0" >> $GITHUB_OUTPUT
        IFS=';' read -ra users_list <<< "$ALLOWED_USERS"
        for user in "${users_list[@]}"; do
          if [[ "$user" == "$actor" ]]; then
            echo "IS_ALLOWED=1" >> $GITHUB_OUTPUT
          fi
        done
    - name: Check if inputs combination is correct
      id: check-inputs
      run: |
        deployment_type=${{ inputs.type }}
        deployment_env=${{ inputs.environment }}
        echo "IS_CORRECT=0" >> $GITHUB_OUTPUT
        if [[ "$deployment_env" == "prod" ]]; then
          if [[ $deployment_type == hotfix_* || $deployment_type == release_* ]]; then
            echo "IS_CORRECT=1" >> $GITHUB_OUTPUT
          fi
        else
          if [[ $deployment_type == hotfix_* || $deployment_type == release_* || $deployment_type == custom_* ]]; then
            echo "IS_CORRECT=1" >> $GITHUB_OUTPUT
          fi
        fi

  prepare-env:
    needs:
      - check-before-run
    if: needs.check-before-run.outputs.IS_ALLOWED == 0 || needs.check-before-run.outputs.IS_CORRECT == 0
    runs-on: ubuntu-22.04
    steps:
    - name: Test
      id: test-condition
      run: |
        echo "IS_ALLOWED={{ needs.check-before-run.outputs.IS_ALLOWED }}"
        echo "Skip useful jobs - not allowed for user"
  get-tag:
    needs:
      - check-before-run
    if: needs.check-before-run.outputs.IS_ALLOWED > 0
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: show GITHUB_REF_NAME
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"