name: badges
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
  release:
    types: [published, edited]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read environment file
        run: |
          while IFS= read -r line; do
            key=$(echo $line | cut -d'=' -f1)
            value=$(echo $line | cut -d'=' -f2)
            value=$(echo -n "$value" | tr -d '\r\n')
            echo "$key=$value" >> $GITHUB_ENV
          done < .env
          shell: bash
      - name: Verify Versions
        run: |
          echo "KUBE_VERSION is $KUBE_VERSION"
          echo "HELM_VERSION is $HELM_VERSION"
          echo "YQ_VERSION is $YQ_VERSION"
          echo "ARGOCD_VERSION is $ARGOCD_VERSION"
          echo "AWSCLI_VERSION is $AWSCLI_VERSION"
      - name: Update badges
        uses: wow-actions/add-badges@v1
        env:
          KUBE_VERSION: ${{ env.KUBE_VERSION }}
          HELM_VERSION: ${{ env.HELM_VERSION }}
          YQ_VERSION: ${{ env.YQ_VERSION }}
          repo_url: ${{ github.event.repository.html_url }}
          repo_name: ${{ github.event.repository.name }}
          repo_owner: ${{ github.event.repository.owner.login }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          badges: |
            [
              {
                "badge": "https://img.shields.io/github/license/${{ env.repo_owner }}/${{ env.repo_name }}?style=flat-square",
                "alt": "MIT License",
                "link": "${{ env.repo_url }}/blob/master/LICENSE"
              },
              {
                "badge": "https://img.shields.io/static/v1?label=&labelColor=black&message=helm-v${{ env.HELM_VERSION }}&color=0076D6&style=flat-square&logo=helm&logoColor=blue",
                "alt": "Helm version",
                "link": "https://github.com/helm/helm/releases/tag/v${{ env.HELM_VERSION }}"
              }
            ]
